name: Swift Package Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.10'

      - name: Build and test
        run: swift test --parallel
